{
 "title": "Moleculer",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": "label_values(moleculer_broker_started{}, namespace)"
   },
   {
    "name": "instance",
    "query": "label_values(moleculer_broker_started{namespace=~\"$namespace\"}, instance)"
   },
   {
    "name": "nodeID",
    "query": "label_values(moleculer_broker_started{namespace=~\"$namespace\", instance=~\"$instance\"}, nodeID)"
   },
   {
    "name": "service",
    "query": "label_values(moleculer_request_total{namespace=~\"$namespace\", instance=~\"$instance\", nodeID=~\"$nodeID\"}, service)"
   },
   {
    "name": "action",
    "query": "label_values(moleculer_request_total{namespace=~\"$namespace\", instance=~\"$instance\", nodeID=~\"$nodeID\",service=~\"$service\"}, action)"
   }
  ]
 },
 "panels": [
  {
   "title": "Nodes",
   "type": "stat",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "max(moleculer_registry_nodes_total{instance=~\"$instance\", namespace=~\"$namespace\", nodeID=~\"$nodeID\"})"
    }
   ]
  },
  {
   "title": "Services",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "max(moleculer_registry_services_total{instance=~\"$instance\", namespace=~\"$namespace\", nodeID=~\"$nodeID\"})"
    }
   ]
  },
  {
   "title": "Actions",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "max(moleculer_registry_actions_total{instance=~\"$instance\", namespace=~\"$namespace\", nodeID=~\"$nodeID\"})"
    }
   ]
  },
  {
   "title": "Events",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "max(moleculer_registry_events_total{instance=~\"$instance\", namespace=~\"$namespace\", nodeID=~\"$nodeID\"})"
    }
   ]
  },
  {
   "title": "Total calls",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(moleculer_request_total{instance=~\"$instance\", namespace=~\"$namespace\", nodeID=~\"$nodeID\", service=~\"$service\", action=~\"$action\"})"
    }
   ]
  },
  {
   "title": "Total errors",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(moleculer_request_error_total{instance=~\"$instance\", namespace=~\"$namespace\", nodeID=~\"$nodeID\", service=~\"$service\", action=~\"$action\"})"
    }
   ]
  },
  {
   "title": "Response time",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(irate(moleculer_request_time_sum{instance=~\"$instance\", namespace=~\"$namespace\", nodeID=~\"$nodeID\", service=~\"$service\", action=~\"$action\"}[1m]))"
    }
   ]
  },
  {
   "title": "Rps",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(irate(moleculer_request_total{instance=~\"$instance\", namespace=~\"$namespace\", nodeID=~\"$nodeID\", service=~\"$service\", action=~\"$action\"}[1m]))"
    }
   ]
  },
  {
   "title": "Response time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "avg(irate(moleculer_request_time_sum{instance=~\"$instance\", namespace=~\"$namespace\", nodeID=~\"$nodeID\", service=~\"$service\", action=~\"$action\"}[1m]))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Action calls",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(moleculer_request_total{instance=~\"$instance\", namespace=~\"$namespace\", nodeID=~\"$nodeID\", service=~\"$service\", action=~\"$action\"}[1m]))",
     "legendFormat": "Calls"
    },
    {
     "expr": "sum(irate(moleculer_request_error_total{instance=~\"$instance\", namespace=~\"$namespace\", nodeID=~\"$nodeID\", service=~\"$service\", action=~\"$action\"}[1m]))",
     "legendFormat": "Errors"
    }
   ]
  },
  {
   "title": "Error types",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (errorName) (irate(moleculer_request_error_total{instance=~\"$instance\", namespace=~\"$namespace\", nodeID=~\"$nodeID\", service=~\"$service\", action=~\"$action\"}[1m]))",
     "legendFormat": "{{errorName}}"
    }
   ]
  },
  { "title": "Alerts", "type": "alertlist", "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 } },
  {
   "title": "Available nodes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "moleculer_registry_nodes_total{instance=~\"$instance\", namespace=~\"$namespace\", nodeID=~\"$nodeID\"}"
    }
   ]
  }
 ]
}